# Generated by Django 2.2.7 on 2019-11-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'The Authors'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': 'The Choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'The Questions'},
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
