# Generated by Django 2.2.7 on 2019-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20191119_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorClone',
            fields=[
            ],
            options={
                'verbose_name_plural': 'The Authors clone',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backoffice.author',),
        ),
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
